#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

use App\Helpers\CsvFileReader;
use App\Helpers\Reporter;
use App\Models\MableAccount;
use App\Services\AccountBalanceLoader;
use App\Services\TransferProcessor;

if (PHP_VERSION_ID < 80400) {
    fwrite(STDERR, "Requires PHP 8.4 or newer, got: " . PHP_VERSION . PHP_EOL);
    exit(1);
}

$balancesFilePath = $argv[1] ?? null;
$transfersFilePath = $argv[2] ?? null;

if ($balancesFilePath === null || $transfersFilePath === null) {
    fwrite(STDERR, "Usage: ./" . PATHINFO_FILENAME . " <balances.csv> <transfers.csv>" . PHP_EOL);
    exit(1);
}

$csvFileReader = new CsvFileReader();
$reporter = new Reporter();

$loadResult = new AccountBalanceLoader($csvFileReader)->load($balancesFilePath);
echo $reporter->reportBalanceLoad($balancesFilePath, $loadResult) . PHP_EOL;


$transferResults = new TransferProcessor(
        $csvFileReader, 
        MableAccount::class
    )->process($transfersFilePath, $loadResult->accounts);
// @TODO: output;

echo "All done." . PHP_EOL;
exit(0);
